site_name: 'Vapor Docs'
copyright: 'Copyright &copy; 2017 Qutheory, LLC'

pages:
- Overview: 'index.md'
- Getting started:
    - 'Install: macOS': 'getting-started/install-on-macos.md'
    - 'Install: Ubuntu': 'getting-started/install-on-ubuntu.md'
    - 'Toolbox': 'getting-started/toolbox.md'
    - 'Hello, World': 'getting-started/hello-world.md'
    - 'Manual': 'getting-started/manual.md'
    - 'Xcode': 'getting-started/xcode.md'
- Vapor:
    - 'Folder Structure': 'vapor/folder-structure.md'
    - 'Droplet': 'vapor/droplet.md'
    - 'Views': 'vapor/views.md'
    - 'Controllers': 'vapor/controllers.md'
    - 'Middleware': 'vapor/middleware.md'
    - 'Validation': 'vapor/validation.md'
    - 'Provider': 'vapor/provider.md'
    - 'Hash': 'vapor/hash.md'
    - 'Log': 'vapor/log.md'
    - 'Commands': 'vapor/commands.md'
- Settings:
    - 'Config': 'settings/config.md'
- JSON:
    - 'JSON': 'json/json.md'
- Routing:
    - 'Basic': 'routing/basic.md'
    - 'Route Parameters': 'routing/parameters.md'
    - 'Query Parameters': 'routing/query-parameters.md'
    - 'Group': 'routing/group.md'
    - 'Collection': 'routing/collection.md'
- Fluent:
    - 'Getting Started': 'fluent/getting-started.md'
    - 'Driver': 'fluent/driver.md'
    - 'Model': 'fluent/model.md'
    - 'Query': 'fluent/query.md'
    - 'Relation': 'fluent/relation.md'
    - 'Package': 'fluent/package.md'
- Auth:
    - 'Getting Started': 'auth/getting-started.md'
    - 'Helper': 'auth/helper.md'
    - 'Password': 'auth/password.md'
    - 'Persist': 'auth/persist.md'
    - 'Package': 'auth/package.md'
- Sessions:
    - 'Sessions': 'sessions/sessions.md'
- HTTP:
    - 'Request': 'http/request.md'
    - 'Response': 'http/response.md'
    - 'Body': 'http/body.md'
    - 'ResponseRepresentable': 'http/response-representable.md'
    - 'Responder': 'http/responder.md'
    - 'Client': 'http/client.md'
    - 'Server': 'http/server.md'
    - 'CORS': 'http/cors.md'
- Leaf:
    - 'Overview': 'leaf/leaf.md'
- Advanced:
    - 'Modules': 'advanced/modules.md'

markdown_extensions:
    - admonition
    - codehilite(guess_lang=false)
    - footnotes
    - meta
    - toc(permalink=true)

theme: 'material'
theme_dir: 'vapor-material'
repo_url: https://github.com/vapor/documentation

extra_css:
  - 'stylesheets/extra.css'
edit_uri: edit/master/2.0/docs/
extra:
    logo: 'images/droplet-white.svg'
    social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'
    font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'
    
google_analytics:
    - 'UA-76177358-4'
    - 'auto'
