site_name: 'Vapor Docs'
copyright: 'Copyright &copy; 2017 Qutheory, LLC'
markdown_extensions:
      - admonition
      - codehilite(guess_lang=false)
      - footnotes
      - meta
      - toc(permalink=true)

pages:
- Overview: 'index.md'
- Getting started:
    - 'Install Swift 3.1: macOS': 'getting-started/install-swift-3-macos.md'
    - 'Install Swift 3.1: Ubuntu': 'getting-started/install-swift-3-ubuntu.md'
    - 'Install Toolbox': 'getting-started/install-toolbox.md'
    - 'Hello, World': 'getting-started/hello-world.md'
    - 'Manual': 'getting-started/manual.md'
    - 'Xcode': 'getting-started/xcode.md'
- Guide:
    - 'Droplet': 'guide/droplet.md'
    - 'Folder Structure': 'guide/folder-structure.md'
    - 'JSON': 'guide/json.md'
    - 'Config': 'guide/config.md'
    - 'Views': 'guide/views.md'
    - 'Leaf': 'guide/leaf.md'
    - 'Controllers': 'guide/controllers.md'
    - 'Middleware': 'guide/middleware.md'
    - 'Validation': 'guide/validation.md'
    - 'Provider': 'guide/provider.md'
    - 'Sessions': 'guide/sessions.md'
    - 'Hash': 'guide/hash.md'
    - 'Commands': 'guide/commands.md'
- Routing:
    - 'Basic': 'routing/basic.md'
    - 'Route Parameters': 'routing/parameters.md'
    - 'Query Parameters': 'routing/query-parameters.md'
    - 'Group': 'routing/group.md'
    - 'Collection': 'routing/collection.md'
- Fluent:
    - 'Driver': 'fluent/driver.md'
    - 'Model': 'fluent/model.md'
    - 'Query': 'fluent/query.md'
    - 'Relation': 'fluent/relation.md'
- Auth:
    - 'User': 'auth/user.md'
    - 'Middleware': 'auth/middleware.md'
    - 'Request': 'auth/request.md'
    - 'Protect': 'auth/protect.md'
- HTTP:
    - 'Request': 'http/request.md'
    - 'Response': 'http/response.md'
    - 'Body': 'http/body.md'
    - 'ResponseRepresentable': 'http/response-representable.md'
    - 'Responder': 'http/responder.md'
    - 'Client': 'http/client.md'
    - 'Server': 'http/server.md'
    - 'CORS': 'http/cors.md'
theme: 'material'
theme_dir: 'vapor-material'
repo_url: https://github.com/vapor/documentation
extra_css:
  - 'stylesheets/extra.css'
edit_uri: edit/master/2.0/docs/
extra:
      logo: 'images/droplet-white.svg'
      social:
        - type: 'twitter'
          link: 'https://twitter.com/@codevapor'
        - type: 'slack'
          link: 'http://vapor.team/'
      font:
        text: 'Roboto Slab'
        code: 'Source Code Pro'
google_analytics:
  - 'UA-76177358-4'
  - 'auto'
